name: "Release"
env:
  FORCE_COLOR: '1'
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 'latest'

jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun i

    - name: Build
      env:
        PUBLIC_URL: "${{github.event.repository.name}}"
      run: bun storybook:build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./storybook-static
